### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by smaaragd** [idf/commons-util#1]
Failed tests:   testSerialize(io.deepreader.java.commons.util.SerializerTest): e
xpected:<[0[.00000,1.00000,2.]00000]> but was:<[0[,00000,1,00000,2,]00000]>

I am trying to build a JAR out of this project, so I can include it in your rake4j Project. However the test fails. The common way of using the Maven dependency didnt work (wrong dependency?) 
  <dependency>
            <groupId>io.deepreader.java.commons</groupId>
            <artifactId>commons-util</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

**Comment by idf** [comment]
Can you have a PR to fix it? Thanks!

**Comment by smaaragd** [comment]
Sure but I keep getting 403 errors when trying to push or create a pull request. Tried with following settings in .git/config:
[remote "origin"]
               url = ssh://git@github.com/idf/commons-util

and

[remote "origin"]
               url = https://github.com/idf/commons-util

Is your repo read only?

Von: Daniel D. Zhang [mailto:notifications@github.com]
Gesendet: Donnerstag, 5. Oktober 2017 06:52
An: idf/commons-util <commons-util@noreply.github.com>
Cc: Shadi Rashed <shadi.rashed@iqblade.com>; Author <author@noreply.github.com>
Betreff: Re: [idf/commons-util] Test fails (#1)


Can you have a PR to fix it? Thanks!

**Comment by idf** [comment]
you should fork this repo https://help.github.com/articles/about-pull-requests/

**Comment by idf** [comment]
I am not able to reproduce the failed test.
